services:
  golf_bdd:
    container_name: golf_bdd
    image: mariadb:11.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIA_DB_ROOT_PASSWORD: toor
      MARIA_DB_DATABASE: bddname
      MARIA_DB_USER: roger
      MARIA_DB_PASSWORD: regor
  golf_adminer:
    container_name: golf_adminer
    image: adminer
    ports:
      - 12600:8080
