services:
  golf_bdd:
    container_name: golf_bdd
    image: mariadb:11.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: bddname
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor
  golf_adminer:
    container_name: golf_adminer
    image: adminer
    ports:
      - 12600:8080
