name: 01-2 - Integration SonarQube

on:
  workflow_call

jobs:
  QualityBack:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: back-coverage-report
          path: backend/coverage

      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        with:
          projectBaseDir: ./backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_EPAD_BACK }}

  QualityFront:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: front-coverage-report
          path: frontend/coverage

      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        with:
          projectBaseDir: ./frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_EPAD_FRONT }}