name: 02-2 - Deploy

on:
  workflow_call:
    
jobs:
  AzureDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Compose File
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_LOGIN }} 
          port: ${{ secrets.AZURE_PORT }}
          password: ${{ secrets.AZURE_PASSWORD }}

          source: "./docker-compose.yml"
          target: "."

      - name: Start App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_LOGIN }} 
          port: ${{ secrets.AZURE_PORT }}
          password: ${{ secrets.AZURE_PASSWORD }}

          script: |
            echo ${{ secrets.MONOREPO_PAT }} | docker login ghcr.io -u flartigue64 --password-stdin
            docker pull ghcr.io/flartigue64/cours0625-back:latest
            docker pull ghcr.io/flartigue64/cours0625-front:latest
            docker compose up -d