name: 01 - Integration

on:
  push:
    - develop

jobs:
  #Test_Back_Front:
    #uses: ./.github/workflows/01-1_TestBackFront.yml

  Quality_SonarQube:
    #needs: [Test_Back_Front]
    uses: ./.github/workflows/01-2_SonarQube.yml

  #Security_Snyk: