name: 01 - Integration

on:
  push:
    branches:
      - marcel

jobs:
  Test_Back_Front:
    uses: ./.github/workflows/01-1_TestBackFront.yaml

  Quality_SonarQube:
    needs: [Test_Back_Front]
    uses: ./.github/workflows/01-2_SonarQube.yaml
    secrets: inherit

  # Security_Snyk